[build]
  base = "turf-app"
  command = "npm install && npm run build"
  publish = "turf-app/.next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8.5.0"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out" 