[build]
  base = "turf-app/"
  publish = "out"
  command = "npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "16.14.0"
  
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out" 