[build]
  base = "turf-app/"
  publish = "out"
  command = "npm ci --prefer-offline --no-audit && npm run build"

[build.environment]
  NODE_VERSION = "16.14.0"
  NPM_VERSION = "8.5.0"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  
[dev]
  command = "npm run dev"
  port = 3000
  publish = "out" 