[build]
  base = "turf-app"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "8.5.0"
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs" 