name: Deploy Supabase Edge Functions

on:
  push:
    branches: [main]
    paths:
      - 'lib/supabase/edge-functions/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    name: Deploy Edge Functions
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Supabase CLI
        run: npm install -g supabase
      
      - name: Login to Supabase
        run: echo "$SUPABASE_ACCESS_TOKEN" | supabase login
      
      - name: Prepare directory structure
        run: |
          mkdir -p supabase/functions/refreshTopics
          cp lib/supabase/edge-functions/refreshTopics.ts supabase/functions/refreshTopics/index.ts
      
      - name: Deploy refreshTopics function
        run: supabase functions deploy refreshTopics --project-ref $SUPABASE_PROJECT_REF --no-verify-jwt
      
      - name: Verify deployment
        run: |
          supabase functions list --project-ref $SUPABASE_PROJECT_REF
          echo "Edge functions deployed successfully!" 