name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    env:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN || 'undefined' }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        
      # Add this step to fix ESLint package conflicts
      - name: Fix ESLint package versions
        run: |
          npm uninstall eslint
          npm install eslint@^8.57.0 --save-dev

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli@0.13.x

      - name: Get Vercel Preview URL
        id: get-preview-url
        run: |
          # Wait for Vercel deployment to be ready (max 5 minutes)
          for i in {1..30}; do
            PREVIEW_URL=$(curl -s -H "Authorization: Bearer $VERCEL_TOKEN" \
              "https://api.vercel.com/v6/deployments?projectId=turf&teamId=team_123&state=READY&target=preview&gitSource.commitSha=${{ github.sha }}" \
              | jq -r '.deployments[0].url')
            
            if [ ! -z "$PREVIEW_URL" ] && [ "$PREVIEW_URL" != "null" ]; then
              echo "url=$PREVIEW_URL" >> $GITHUB_OUTPUT
              break
            fi
            
            echo "Waiting for Vercel preview URL... (attempt $i/30)"
            sleep 10
          done

      - name: Run Lighthouse CI
        run: |
          if [ -z "${{ steps.get-preview-url.outputs.url }}" ]; then
            echo "Failed to get Vercel preview URL after 5 minutes"
            exit 1
          fi
          
          lhci autorun \
            --collect.url=${{ steps.get-preview-url.outputs.url }} \
            --collect.numberOfRuns=3 \
            --collect.settings.preset=desktop \
            --upload.target=temporary-public-storage \
            --assert.preset=lighthouse:recommended 